name: Crystal CI

on:
  status:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
